name: Front-end CI

on:
  push:
    branches: [ "main", "dev", "feature/**" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 21.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Set environment variables
      run: |
        export NEXT_PUBLIC_FRONTEND_URL=${{ vars.PUBLIC_FRONTEND_URL }}
        export NEXT_PUBLIC_API_URL=${{ vars.PUBLIC_API_URL }}
    - name: Test build
      run: npm run build --if-present
