name: Front-end CI (Merged)

on:
  push:
    branches: [ "main" ]
    paths: ["**.js", "**.jsx", "**.ts", "**.tsx", "**.json", "**.svg", "**.css", "**.scss"]
  workflow_dispatch:

env:
  IMAGE_NAME: libba-frontend
  IMAGE_TAG: test-${{ github.sha }}


jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 21.x]
    environment: TEST
    env:
      NEXT_PUBLIC_FRONTEND_URL: ${{ vars.PUBLIC_FRONTEND_URL }}
      NEXT_PUBLIC_API_URL:  ${{ vars.PUBLIC_API_URL }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Test build
      run: npm run build --if-present

  Package:
    needs: Build
    if: ${{ success() }}
    runs-on: ubuntu-latest
    environment: TEST
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        build-args: |
          NEXT_PUBLIC_FRONTEND_URL=${{ vars.PUBLIC_FRONTEND_URL }}
          NEXT_PUBLIC_API_URL=${{ vars.PUBLIC_API_URL }}

