name: Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - production
      tag:
        description: 'Image tag to deploy'
        required: true
        default: 'latest'
        type: string
      release_name:
        description: 'Release name for Helm deployment'
        required: false
        default: 'library-manager'
        type: string
      chart_version:
        description: 'Chart version for Helm deployment'
        required: false
        default: '1.0.0'
        type: string


env:
  IMAGE_NAME: libba-frontend
  IMAGE_TAG: ${{ github.event.inputs.tag }}
  CHART_NAME: oci://registry-1.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/library-manager
  CHART_VERSION: ${{ github.event.inputs.chart_version }}
  RELEASE_NAME: ${{ github.event.inputs.release_name }}
  RELEASE_NAMESPACE: ${{ github.event.inputs.environment }}
  

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to ${{ github.event.inputs.environment }} environment
      uses: wahyd4/kubectl-helm-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: |
          helm upgrade ${{ env.RELEASE_NAME }} ${{ env.CHART_NAME }} \
          --namespace ${{ env.RELEASE_NAMESPACE }} \
          --install \
          --version ${{ env.CHART_VERSION }} \
          --set frontend.image.tag=${{ env.IMAGE_TAG }}
